### ISSUE TITLE
Update CP3 pipeline to avoid CreateBatchFile related issues

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/imaging-platform-pipelines#16]
See https://github.com/broadinstitute/cmQTL/issues/14#issuecomment-505547381

**Comment by shntnu** [comment]
I tested that this works ok headless when creating BatchFiles! Next up – also change the illum pipeline

**Comment by shntnu** [comment]
In a second attempt, it didn't seem to work correctly

```
Traceback (most recent call last):
  File "/usr/local/bin/cellprofiler", line 11, in <module>
    load_entry_point('CellProfiler', 'console_scripts', 'cellprofiler')()
  File "/usr/local/src/CellProfiler/cellprofiler/__main__.py", line 122, in main
    raise ValueError("You must specify a pipeline filename to run")
ValueError: You must specify a pipeline filename to run

```
